### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by kasir-barati** [tomwray13/nestjs-caching#5]
Hi, thanks for the wonderful blog post + repo

Could not bring myself to not give you my two cents, so even though it is a bit inappropriate use of GH issues I created one nonetheless :sweat_smile:.

1. Better to use this method, because it is more type safe and easier to validate your end variables: https://github.com/kasir-barati/you-say/blob/main/apps/backend/src/app/configs/app.config.ts
2. Better to use RedisInsight:
    ```yml
   redisinsight:
     image: oblakstudio/redisinsight:latest
     network_mode: host
     ports:
       - 5540:5540
     environment:
       SERVER_TLS: false
    ```
3. Why you have not touched the fact that if we are using `@UseInterceptors(CacheInterceptor)` and `@CacheKey('something')` it is not taking into account the query strings and will return same result for different query strings?
    So here is what has happened to me: I had a get all endpoint with different query strings. But I was using `@CacheKey('get-reports')` and that was causing my endpoint to return same result for different query strings

I again wanna thanks you for your dedication to share your knowledge and I think that is the thing that connect us NestJS devs to each other. Share your know-how.
